#include<iostream.h>
#include<conio.h>

void main()
{
	clrscr();
	cout<<"12==12="<<(12==12)<<endl;
	cout<<"12>11="<<(12>11)<<endl;
	cout<<"12<13="<<(12<13)<<endl;
	cout<<"12>=10="<<(12>=10)<<endl;
	cout<<"12<=12="<<(12<=12)<<endl;
	cout<<"12!=11="<<(12!=11)<<endl<<endl;

	cout<<"12==11="<<(12==11)<<endl;
	cout<<"12>13="<<(12>13)<<endl;
	cout<<"12<11="<<(12<11)<<endl;
	cout<<"12>=13="<<(12>=13)<<endl;
	cout<<"12<=10="<<(12<=10)<<endl;
	cout<<"12!=12="<<(12!=12)<<endl;


	getch();
}